apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: django-app 
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/acme/django-app
  version:
    semver: v1.0.0
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
