apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: django-app
  namespace: ocm-system
spec:
  interval: 1m0s
  componentVersionRef:
    name: django-app
    namespace: ocm-system
  source:
    sourceRef:
      kind: Snapshot
      name: django-app-snapshot-deployment
      namespace: ocm-system
  configRef:
    resource:
      resourceRef:
        name: app-config
  snapshotTemplate:
    name: django-app-deployment-localized
    createFluxSource: true
