apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: db-app
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/acme/db-app
  version:
    semver: v1.1.2
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
